extract_report_structure:
  description: >
    Extract the Table of Contents (TOC) or logical report structure from the uploaded sustainability report.

    The report content has been extracted and provided below. Instructions:
    - First, try to find an explicit TOC section. If found, extract each section title and its page reference.
    - If no formal TOC is found, infer the report's structure by identifying top-level headings based on layout cues like bold formatting, heading numbers (e.g., 1.0, 2.1.1), or all-caps titles.
    - Include only meaningful section titles relevant to ESG or sustainability disclosures (e.g., "GRI Index", "Environmental Performance", "Governance", "Stakeholder Engagement", "TCFD Alignment").
    
    You are allowed to make reasonable assumptions when inferring structure.

    Report content to analyze:
    {report_content}

  expected_output: >
    A list of detected section titles along with any page numbers or location hints (if available).
    Example:
    - Executive Summary (pg. 4)
    - Sustainability Strategy (pg. 6)
    - GRI Index (pg. 25)
    - Climate Risk Disclosures (pg. 31)
  agent: structure_identifier

extract_framework_sections:
  description: >
    From the given report content, extract only the sections that likely mention ESG reporting frameworks.
    Focus on sections about methodology, frameworks used, standards followed, and related disclosures.

    Report content to analyze:
    {report_content}
  expected_output: >
    A structured list of relevant sections and paragraphs extracted from the report text that are likely to identify the ESG reporting frameworks (e.g., GRI, SASB, TCFD, etc.)
  agent: section_filter

  
detect_reporting_framework:
  description: >
    Analyze the content of the uploaded sustainability report and identify which ESG or sustainability reporting frameworks are referenced — either explicitly or implicitly.

    The report content has been extracted and provided below. Focus particularly on sections titled "About this Report", "Methodology", "Reporting Approach", or "Assurance", as these commonly contain framework declarations.

    **CRITICAL CONTEXT ANALYSIS**: Pay close attention to the context and role of each framework mentioned:
    
    - **Primary Framework**: The main framework the report is aligned with or prepared in accordance with
    - **Secondary Framework**: Additional frameworks mentioned but not the primary focus
    - **Reference Framework**: Frameworks mentioned for context or comparison only
    
    **PRIMARY FRAMEWORK INDICATORS (Strongest Evidence - MUST HAVE)**:
    - "prepared in accordance with" = PRIMARY framework (STRONGEST INDICATOR)
    - "this report follows" = PRIMARY framework
    - "we report in accordance with" = PRIMARY framework
    - "the report is prepared following" = PRIMARY framework
    
    **IMPORTANT**: If NO framework uses "prepared in accordance with", then NO framework should be marked as PRIMARY.
    
    **SECONDARY FRAMEWORK INDICATORS (Weaker Evidence)**:
    - "consistent with" = SECONDARY framework (even if "throughout this annual report")
    - "aligned with" = SECONDARY framework (especially for specific sections like climate)
    - "publish against" = SECONDARY framework
    - "voluntary" = SECONDARY framework
    - "additional" = SECONDARY framework
    - "supplementary" = SECONDARY framework
    - "recommendations" = SECONDARY framework (even if "throughout this annual report")
    
    **REFERENCE FRAMEWORK INDICATORS (Weakest Evidence)**:
    - "consideration to" = REFERENCE framework
    - "mentioned for context" = REFERENCE framework
    - "but do not align in full with" = REFERENCE framework
    
    **CRITICAL RULE**: A framework mentioned with "throughout this annual report" but using "consistent with" or "recommendations" should be SECONDARY, not PRIMARY. Only "prepared in accordance with" can make a framework PRIMARY.
    **STRICT CLASSIFICATION GUARDRAILS**:
    - If a framework is mentioned with the words "voluntary", "ESG index", "publish against", "select GRI topics", or "referenced", it MUST NOT be marked as PRIMARY.
    - GRI MUST NOT be PRIMARY unless the phrase "prepared in accordance with the GRI Standards" or similar appears.
    - If no framework uses a PRIMARY-qualifying phrase like "prepared in accordance with", leave PRIMARY empty and only classify SECONDARY or REFERENCE frameworks.
    - Consider which framework the report uses to structure its entire narrative. "Throughout the report" is only valid if paired with a PRIMARY phrase (e.g., "prepared in accordance with").

    The target frameworks to detect include (but are not limited to):
    - GRI Standards
    - IFRS S2 (ISSB)
    - EU CSRD / ESRS
    - TCFD (Task Force on Climate-related Financial Disclosures)
    - SASB (Sustainability Accounting Standards Board)
    - CDP (Carbon Disclosure Project)
    - ISO 14064
    - Ipieca
    - Greenhouse Gas (GHG) Protocol
    - ISAE 3000
    - SDGs (Sustainable Development Goals)

    **ANALYSIS PRIORITY**:
    1. First, identify the PRIMARY framework (the one the report is mainly prepared in accordance with)
    2. Then identify SECONDARY frameworks (additional standards followed)
    3. Finally, identify REFERENCE frameworks (mentioned for context)

    **EXAMPLE ANALYSIS**:
    If a report states: "This Sustainability Report has been prepared in accordance with the GRI Standards. We have also aligned our climate disclosures with the TCFD recommendations."
    
    - GRI would be PRIMARY (prepared in accordance with)
    - TCFD would be SECONDARY (aligned with, for climate section only)

    For each framework detected, provide:
    - The full name of the framework
    - Supporting quote or evidence from the report
    - The framework's role (Primary/Secondary/Reference)
    - Whether the mention is explicit or inferred
    - A confidence score from 0 to 100

    Do not guess. If uncertain, say so clearly.

    Report content to analyze:
    {report_content}
  expected_output: >
    A bullet list in markdown format of the frameworks identified, prioritized by their role in the report. Example:

    - **GRI Standards (PRIMARY)**: "This Sustainability Report has been prepared in accordance with the GRI Standards" — Explicit primary alignment. **Confidence**: 95%
    - **TCFD (SECONDARY)**: "We have also aligned our climate disclosures with the TCFD recommendations" — Secondary alignment for climate section only. **Confidence**: 80%
    - **IFRS S2 (REFERENCE)**: "We have given consideration to IFRS S2" — Mentioned for context only. **Confidence**: 70%
    - **CDP**: Not mentioned or implied. **Confidence**: 10%
  agent: framework_detector
  
remove_report_fluff:
  description: >
    You are tasked with preparing a corporate sustainability report for ESG compliance and greenwashing analysis.

    Your job is to remove all irrelevant, vague, repetitive, or promotional content — while preserving every potentially material statement,
    whether quantitative (e.g. emissions, targets, energy use) or qualitative (e.g. commitments, claims, governance structures).

    **CRITICAL FRAMEWORK PRESERVATION**: If TCFD or GRI frameworks are detected, you MUST preserve ALL content related to these frameworks as it will be analyzed by specialized tools.

    **TCFD CONTENT - MUST PRESERVE:**
    - All climate-related risk and opportunity discussions
    - Board oversight of climate issues (tcfd_1)
    - Management's role in climate risk assessment (tcfd_2)
    - Climate risk identification and time horizons (tcfd_3)
    - Impact on business strategy and financial planning (tcfd_4)
    - Climate scenario analysis and resilience (tcfd_5)
    - Climate risk identification processes (tcfd_6)
    - Climate risk management processes (tcfd_7)
    - Integration with overall risk management (tcfd_8)
    - Climate metrics and performance indicators (tcfd_9)
    - Scope 1, 2, 3 emissions data and methodology (tcfd_10)
    - Climate targets and performance against targets (tcfd_11)
    - Any mention of "climate", "emissions", "GHG", "carbon", "TCFD"

    **GRI CONTENT - MUST PRESERVE:**
    - All GRI indicator mentions (GRI 102, 305, 403, 401, 413, 414, 302, 306, 307, 308)
    - Material topics and stakeholder engagement processes
    - Specific GRI disclosures and reporting methodology
    - Environmental performance data (emissions, energy, waste, water)
    - Social performance data (employment, health & safety, community)
    - Governance disclosures and compliance information
    - Any mention of "GRI", "Global Reporting Initiative", "materiality", "stakeholder"
    - Specific quantitative data related to GRI indicators
    - Reporting boundaries and methodology explanations

    You MUST retain:
    - Any mention of ESG frameworks (GRI, TCFD, SASB, etc.)
    - Specific or vague references to goals, targets, achievements, or strategies
    - Statements on scope 1, 2, or 3 emissions
    - Descriptions of stakeholder engagement or governance processes
    - Risk assessments or opportunity discussions (even if lacking data)
    - Any claim that could later be tested or challenged (even if unverifiable)

    You MUST remove:
    - Marketing filler, slogans, taglines, vision/mission intros repeated across pages
    - CEO letters with no ESG disclosures
    - Repeated boilerplate about the company history, size, or general industry
    - Design artifacts (e.g. page numbers, footers, headers, TOC)
    - Sections unrelated to ESG (e.g. pure financial results unless ESG-linked)

    Be surgical and skeptical. If a sentence feels like fluff but includes ESG vocabulary, keep it.
    Err on the side of **over-preservation** rather than removing useful info.

    Your cleaned output will be passed to agents conducting deep ESG scrutiny.

    Report content to clean:
    {report_content}

    Detected frameworks to preserve:
    {detected_frameworks}
  expected_output: >
    A cleaned full-report text, retaining all ESG-relevant content for analysis.
    Return the output as a single continuous text block with section breaks if possible.
  agent: fluff_remover


extract_esg_claims:
  description: >
    Extract ALL ESG claims from the provided sustainability report content.
    
    **REQUIREMENTS**:
    - Extract ALL specific, verifiable claims (no limit)
    - Include environmental, social, governance, and financial claims
    - Focus on claims that can be tested or challenged
    - Include vague, unverifiable, or potentially misleading statements
    
    **FRAMEWORK ANALYSIS**:
    - If TCFD detected: Use TCFDAnalyzerTool with analysis_type="comprehensive"
    - If GRI detected: Use GRIAnalyzerTool with analysis_type="comprehensive"
    - If SASB detected: Use FrameworkGlossaryTool for industry-specific analysis
    
    **OUTPUT FORMAT**:
    ## ESG Claims Extracted
    ### Environmental Claims: [List ALL]
    ### Social Claims: [List ALL]
    ### Governance Claims: [List ALL]
    ### Financial Claims: [List ALL]
    ### Vague Claims: [List ALL]
    ### Missing Disclosures: [List ALL]
    
    For each claim provide: Claim, Category, Context, Specificity, Verifiability, Framework Alignment, Potential Issues
    
    ## Framework Analysis
    ### [Framework] Analysis
    - Compliance Score: X%
    - Claims: [Complete list]
    - Missing Elements: [Complete list]
    - Recommendations: [Complete list]
    
    Analyze the following report content thoroughly:
    {esg_content}
  expected_output: >
    Comprehensive structured analysis with ALL ESG claims, framework compliance assessments, and complete greenwashing indicators.
  agent: esg_analyst

validate_claims:
  description: >
    Analyze ALL ESG claims for potential greenwashing in a comprehensive audit.
    
    **ANALYSIS REQUIREMENTS**:
    - Analyze ALL claims provided by the ESG Analyst (no limit)
    - Look for vague language, missing targets, lack of verification
    - Identify inconsistencies, cherry-picking, and missing disclosures
    - Evaluate specificity, time-bound commitments, evidence, and transparency
    
    **GREENWASHING INDICATORS**:
    - Vague language: "committed to sustainability", "working towards"
    - No specific targets, timelines, or baselines
    - Lack of baseline data or methodology
    - Overly positive claims without evidence
    - Cherry-picking positive data while ignoring negative aspects
    - Using buzzwords without substance
    - Claims that sound good but lack verifiability
    
    **OUTPUT FORMAT**:
    ## ESG Claims Greenwashing Analysis
    
    ### Environmental Claims Analysis: [Analyze ALL]
    ### Social Claims Analysis: [Analyze ALL]
    ### Governance Claims Analysis: [Analyze ALL]
    ### Financial Claims Analysis: [Analyze ALL]
    ### Vague Claims Analysis: [Analyze ALL]
    ### Missing Disclosures Analysis: [Analyze ALL]
    
    For each claim provide: Claim, Greenwashing Flag (YES/NO), Confidence Score (0-100%), Critical Analysis, Evidence Assessment, Recommendations, Risk Level (High/Medium/Low)
    
    ## Framework-Specific Greenwashing Assessment
    ### TCFD Greenwashing Analysis: [If TCFD detected]
    ### GRI Greenwashing Analysis: [If GRI detected]
    ### SASB Greenwashing Analysis: [If SASB detected]
    
    Analyze the following ESG Analyst output thoroughly:
    {esg_analyst_output}
  expected_output: >
    Comprehensive greenwashing analysis with detailed assessment of ALL claims, framework-specific validation, and complete risk assessment.
  agent: compliance_checker
