extract_report_structure:
  description: >
    Extract the Table of Contents (TOC) or logical report structure from the uploaded sustainability report.

    The report content has been extracted and provided below. Instructions:
    - First, try to find an explicit TOC section. If found, extract each section title and its page reference.
    - If no formal TOC is found, infer the report's structure by identifying top-level headings based on layout cues like bold formatting, heading numbers (e.g., 1.0, 2.1.1), or all-caps titles.
    - Include only meaningful section titles relevant to ESG or sustainability disclosures (e.g., "GRI Index", "Environmental Performance", "Governance", "Stakeholder Engagement", "TCFD Alignment").
    
    You are allowed to make reasonable assumptions when inferring structure.

    Report content to analyze:
    {report_content}

  expected_output: >
    A list of detected section titles along with any page numbers or location hints (if available).
    Example:
    - Executive Summary (pg. 4)
    - Sustainability Strategy (pg. 6)
    - GRI Index (pg. 25)
    - Climate Risk Disclosures (pg. 31)
  agent: structure_identifier

extract_framework_sections:
  description: >
    From the given report content, extract only the sections that likely mention ESG reporting frameworks.
    Focus on sections about methodology, frameworks used, standards followed, and related disclosures.

    Report content to analyze:
    {report_content}
  expected_output: >
    A structured list of relevant sections and paragraphs extracted from the report text that are likely to identify the ESG reporting frameworks (e.g., GRI, SASB, TCFD, etc.)
  agent: section_filter

  
detect_reporting_framework:
  description: >
    Analyze the content of the uploaded sustainability report and identify which ESG or sustainability reporting frameworks are referenced — either explicitly or implicitly.

    The report content has been extracted and provided below. Focus particularly on sections titled "About this Report", "Methodology", "Reporting Approach", or "Assurance", as these commonly contain framework declarations.

    The target frameworks to detect include (but are not limited to):
    - GRI Standards
    - IFRS S2 (ISSB)
    - EU CSRD / ESRS
    - TCFD (Task Force on Climate-related Financial Disclosures)
    - SASB (Sustainability Accounting Standards Board)
    - CDP (Carbon Disclosure Project)
    - ISO 14064
    - Ipieca
    - Greenhouse Gas (GHG) Protocol
    - ISAE 3000
    - SDGs (Sustainable Development Goals)

    For each framework detected, provide:
    - The full name of the framework
    - Supporting quote or evidence from the report
    - Whether the mention is explicit or inferred
    - A confidence score from 0 to 100

    Do not guess. If uncertain, say so clearly.

    Report content to analyze:
    {report_content}
  expected_output: >
    A bullet list in markdown format of the frameworks identified. Example:

    - **GRI Standards**: Mentioned explicitly on page 5 under "About this Report" — "This report is prepared in accordance with the GRI Standards: Core option". **Confidence**: 98%
    - **TCFD**: Not explicitly mentioned, but climate risk alignment and governance indicators are used. **Confidence**: 65%
    - **CDP**: Not mentioned or implied. **Confidence**: 10%
  agent: framework_detector
  
remove_report_fluff:
  description: >
    You are tasked with preparing a corporate sustainability report for ESG compliance and greenwashing analysis.

    Your job is to remove all irrelevant, vague, repetitive, or promotional content — while preserving every potentially material statement,
    whether quantitative (e.g. emissions, targets, energy use) or qualitative (e.g. commitments, claims, governance structures).

    You MUST retain:
    - Any mention of ESG frameworks (GRI, TCFD, SASB, etc.)
    - Specific or vague references to goals, targets, achievements, or strategies
    - Statements on scope 1, 2, or 3 emissions
    - Descriptions of stakeholder engagement or governance processes
    - Risk assessments or opportunity discussions (even if lacking data)
    - Any claim that could later be tested or challenged (even if unverifiable)

    You MUST remove:
    - Marketing filler, slogans, taglines, vision/mission intros repeated across pages
    - CEO letters with no ESG disclosures
    - Repeated boilerplate about the company history, size, or general industry
    - Design artifacts (e.g. page numbers, footers, headers, TOC)
    - Sections unrelated to ESG (e.g. pure financial results unless ESG-linked)

    Be surgical and skeptical. If a sentence feels like fluff but includes ESG vocabulary, keep it.
    Err on the side of **over-preservation** rather than removing useful info.

    Your cleaned output will be passed to agents conducting deep ESG scrutiny.

    Report content to clean:
    {report_content}
  expected_output: >
    A cleaned full-report text, retaining all ESG-relevant content for analysis.
    Return the output as a single continuous text block with section breaks if possible.
  agent: fluff_remover


extract_esg_claims:
  description: >
    Read and analyze the complete sustainability report content provided in {esg_content}. This content includes ALL sections of the document, processed from multiple chunks to ensure comprehensive coverage.

    Extract up to 5 key ESG-related claims made by the company. Focus on statements related to environmental impact,
    carbon neutrality goals, social initiatives, or sustainability commitments.

    IMPORTANT: Analyze ALL sections provided in the content to ensure you capture claims from throughout the entire document, not just the beginning.

    FRAMEWORK-SPECIFIC ANALYSIS:
    Based on the frameworks detected in the report, perform additional specialized analysis:
    
    - If TCFD (Task Force on Climate-related Financial Disclosures) is detected: Use the TCFDAnalyzerTool to perform detailed TCFD compliance analysis across all four pillars (Governance, Strategy, Risk Management, Metrics & Targets). Provide compliance scores, identify missing elements, and detect potential greenwashing signals.
    
    - If GRI Standards are detected: Use the FrameworkGlossaryTool to understand GRI requirements and assess alignment with specific GRI indicators mentioned in the report.
    
    - If SASB is detected: Use the FrameworkGlossaryTool to evaluate industry-specific materiality and financial impact disclosures.
    
    For each framework detected, provide:
    1. Framework-specific compliance assessment
    2. Missing required disclosures
    3. Potential greenwashing indicators
    4. Recommendations for improvement

    Make sure the claims are concise and represent the core messaging from the document.
  expected_output: >
    A comprehensive analysis including:
    1. A list of 5 distinct ESG-related claims with short descriptions or context snippets
    2. Framework-specific analysis for each detected framework (TCFD, GRI, SASB, etc.)
    3. Compliance scores and missing elements for each framework
    4. Greenwashing detection results with confidence scores
    5. Specific recommendations for improvement
  agent: esg_analyst

validate_claims:
  description: >
    Review each ESG claim using internal reasoning and knowledge of sustainability standards.
    You will analyze the claims against established ESG frameworks and best practices.
    
    The claims to validate are extracted from the complete document content provided in {claims_content}, which includes ALL sections of the sustainability report.
    
    For each claim, evaluate:
      - Specificity and measurability of targets
      - Time-bound commitments and deadlines
      - Alignment with recognized sustainability standards
      - Presence of third-party verification or certification
      - Clarity and transparency of reporting
      - Potential for greenwashing based on vague or unverifiable language
    
    Apply evaluation criteria such as:
      - GRI Standards for reporting quality
      - SASB metrics for materiality
      - TCFD recommendations for climate disclosures
      - General principles of credible sustainability reporting
    
    For each claim:
      - Determine if it is vague, unverifiable, or exaggerated
      - Assess measurability and specificity
      - Check for time-bound commitments
      - Look for third-party certifications or standards
      - Provide a greenwashing flag (Yes/No)
      - Assign a confidence score from 0–100
      - Write a brief explanation of your decision
    
    Example evaluation:
    Claim: "We aim to reduce emissions"
    Greenwashing: YES
    Reason: Vague, lacks baseline, target, and timeline
    Confidence: 85%
    
    Your final answer MUST be in markdown format with one section per claim.
  expected_output: >
    A markdown report containing:
    - Each ESG claim
    - Greenwashing flag (Yes/No)
    - Confidence score (0–100)
    - Explanation based on framework analysis
  agent: compliance_checker
